### ISSUE TITLE
Patch for support for Arduino 1.0 and above

### ISSUE THREAD

**Issue by RobTillaart** [milesburton/HT1632#1]
Hi Miles,

From the forum - http://forum.arduino.cc/index.php?topic=179661.msg1331623#msg1331623 - 

don't know if it is the ultimate patch but I got the simple patch compiling this way.

```
#ifndef MATRIX_DISPLAY_GUARD
#define MATRIX_DISPLAY_GUARD

#if ARDUINO < 100
#include <WProgram.h>
#include <wiring.h>
#else
#include <Arduino.h>
#endif

#include <inttypes.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>

#include "HardwareSerial.h"
```

**Comment by RobTillaart** [comment]
Something manipulated the code, sorry, see the forum link for a good code smaple,
Rob

**Comment by milesburton** [comment]
Thanks Rob, let me investigate

**Comment by q2dg** [comment]
Well...

**Comment by RobTillaart** [comment]
@q2dg 
updated post above to reflect the patch

**Comment by milesburton** [comment]
Sorry guys, I've totally overlooked this issue. 

That said, am I being blind. Looking at the code, whilst not being in standard for Arduino 1.0 (I'll look into that). It does include the appropriate macro for arduino 1 as per Rob's patch.

What am I missing?

**Comment by RobTillaart** [comment]
AFAIK nothing, I just added the patch code in comment #1 as reaction on q2dg's question.
Think the issue should be closed as the patch is in.

**Comment by decpad** [comment]
Hello

Is it possible to use your libraries for a Sure Matrix 24x16 with a HT1632C-Chip? 

When yes, how?

Thanks a lot
